"use client"

import { Exercise, columns } from "@/components/data-table/columns"
import { DataTable } from "@/components/data-table/data-table"

function getData1(): Exercise[]{
    return [
        {
            day: "Full Body 1",             
            exercise: "Back Squat",         
            warmup_sets: 4,      
            working_sets: 1,     
            reps: 2,             
            load: 320,             
            percent: 87.5,          
            rpe: 7,              
            rest_time: 4,        
            actual: 320,           
            notes: "",   
        },
        {
            day: "",             
            exercise: "Front squat (or box squat)",         
            warmup_sets: 0,      
            working_sets: 3,     
            reps: 8,             
            load: 0,             
            percent: 0,          
            rpe: 7,              
            rest_time: 4,        
            actual: 135,           
            notes: "",            
        },
        {
            day: "",             
            exercise: "Barbell bench press",         
            warmup_sets: 4,      
            working_sets: 1,     
            reps: 4,             
            load: 215,             
            percent: 85,          
            rpe: 8.5,              
            rest_time: 4,        
            actual: 215,           
            notes: "",            
        },
        {
            day: "",             
            exercise: "Barbell bench press",        
            warmup_sets: 0,      
            working_sets: 2,     
            reps: 6,             
            load: 205,             
            percent: 80,          
            rpe: 7,              
            rest_time: 2,        
            actual: 205,           
            notes: "",           
        },
        {
            day: "",             
            exercise: "Weighted pull-up",         
            warmup_sets: 1,      
            working_sets: 3,     
            reps: 6,             
            load: 0,             
            percent: 0,          
            rpe: 8,              
            rest_time: 2,        
            actual: 180,           
            notes: "",            
        },
        {
            day: "",             
            exercise: "Glute-ham raise (or Nordic ham curl)",         
            warmup_sets: 1,      
            working_sets: 3,     
            reps: 8,             
            load: 0,             
            percent: 0,          
            rpe: 7,              
            rest_time: 2,        
            actual: 180,           
            notes: "",           
        },
        {
            day: "",             
            exercise: "Seated face pull",         
            warmup_sets: 0,      
            working_sets: 4,     
            reps: 20,             
            load: 0,             
            percent: 0,          
            rpe: 9,              
            rest_time: 2,        
            actual: 50,           
            notes: "",           
        }
    ]
}

function getData2(): Exercise[]{
    return [
        {
            day: "Full Body 2",             
            exercise: "Deadlift",         
            warmup_sets: 4,      
            working_sets: 3,     
            reps: 4,             
            load: 360,             
            percent: 80,          
            rpe: 7,              
            rest_time: 5,        
            actual: 365,           
            notes: "",   
        },
        {
            day: "",             
            exercise: "Barbell Overhead Press",         
            warmup_sets: 3,      
            working_sets: 4,     
            reps: 5,             
            load: 110,             
            percent: 75,          
            rpe: 8,              
            rest_time: 4,        
            actual: 110,           
            notes: "",            
        },
        {
            day: "",             
            exercise: "Bulgarian Split Squat",         
            warmup_sets: 1,      
            working_sets: 2,     
            reps: 10,             
            load: 0,             
            percent: 0,          
            rpe: 9,              
            rest_time: 3,        
            actual: 35,           
            notes: "",            
        },
        {
            day: "",             
            exercise: "Meadows Row",        
            warmup_sets: 1,      
            working_sets: 4,     
            reps: 15,             
            load: 0,             
            percent: 0,          
            rpe: 8,              
            rest_time: 3,        
            actual: 40,           
            notes: "",           
        },
        {
            day: "",             
            exercise: "Barbell or EZ bar curl",         
            warmup_sets: 1,      
            working_sets: 3,     
            reps: 10,             
            load: 0,             
            percent: 0,          
            rpe: 8,              
            rest_time: 2,        
            actual: 55,           
            notes: "",            
        },
        {
            day: "",             
            exercise: "Pec Flye",         
            warmup_sets: 1,      
            working_sets: 2,     
            reps: 15,             
            load: 0,             
            percent: 0,          
            rpe: 8,              
            rest_time: 2,        
            actual: 60,           
            notes: "",           
        }
    ]
}
  
function getData3(): Exercise[]{
    return [
        {
            day: "Full Body 3",             
            exercise: "Back Squat",         
            warmup_sets: 4,      
            working_sets: 1,     
            reps: 6,             
            load: 290,             
            percent: 80,          
            rpe: 7,              
            rest_time: 4,        
            actual: 285,           
            notes: "",   
        },
        {
            day: "",             
            exercise: "Pin Squat",         
            warmup_sets: 0,      
            working_sets: 2,     
            reps: 4,             
            load: 255,             
            percent: 70,          
            rpe: 8,              
            rest_time: 4,        
            actual: 255,           
            notes: "",            
        },
        {
            day: "",             
            exercise: "Barbell Bench Press",         
            warmup_sets: 4,      
            working_sets: 1,     
            reps: 1,             
            load: 235,             
            percent: 92.5,          
            rpe: 8,              
            rest_time: 4,        
            actual: 235,           
            notes: "",            
        },
        {
            day: "",             
            exercise: "Barbell Bench Press",        
            warmup_sets: 0,      
            working_sets: 1,     
            reps: 5,             
            load: 205,             
            percent: 80,          
            rpe: 8,              
            rest_time: 4,        
            actual: 205,           
            notes: "",           
        },
        {
            day: "",             
            exercise: "Barbell Bench Press",         
            warmup_sets: 0,      
            working_sets: 1,     
            reps: 10,             
            load: 165,             
            percent: 65,          
            rpe: 8,              
            rest_time: 4,        
            actual: 165,           
            notes: "",            
        },
        {
            day: "",             
            exercise: "Chin-up",         
            warmup_sets: 1,      
            working_sets: 3,     
            reps: 15,             
            load: 0,             
            percent: 0,          
            rpe: 8,              
            rest_time: 4,        
            actual: 0,           
            notes: "",           
        },
        {
          day: "",             
          exercise: "Single-leg Hip Thrust",         
          warmup_sets: 0,      
          working_sets: 2,     
          reps: 12,             
          load: 0,             
          percent: 0,          
          rpe: 8,              
          rest_time: 2,        
          actual: 185,           
          notes: "",           
        },
        {
          day: "",             
          exercise: "Cable Reverse Flye",         
          warmup_sets: 0,      
          working_sets: 4,     
          reps: 15,             
          load: 0,             
          percent: 0,          
          rpe: 8,              
          rest_time: 2,        
          actual: 20,           
          notes: "",           
        }
      ]
}

export function PlanForm() {
    return (
        <div>
            {/*<h1 className="text-center">Plan Page</h1>*/}
            <div>
                <DataTable columns={columns} data={getData1()} />
                <DataTable columns={columns} data={getData2()} />
                <DataTable columns={columns} data={getData3()} />      
            </div>
        </div>
    )
}